# Generated by Django 3.0.8 on 2022-09-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='data',
            name='sku',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='data',
            name='vendor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='data',
            name='week',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='weekly_sales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
